#-------------------------------
# General Site Info

email: hello@pgh.codes
url: "http://www.pgh.codes" # the base hostname & protocol for your site

# Base SEO
seo:
    title: Trash Connect / Codefest 2016
    description: "Trash Connect / Codefest 2016"